language: scala

scala:
  - 2.11.7
jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/

install: /bin/true

script:
  - sbt ++$TRAVIS_SCALA_VERSION -jvm-opts travis-jvmopts clean test
